development: &default
  adapter: postgresql
  database: todoism
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: todoism_test

production:
  <<: *default
  database: todoism_production